# Generated by Django 4.2.4 on 2023-08-29 19:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("todos", "0003_todoitem_todo_list"),
    ]

    operations = [
        migrations.RenameField(
            model_name="todoitem",
            old_name="todo_list",
            new_name="list",
        ),
    ]
